In [1]:
import numpy as np

------------------------------------------------------------------------------------------------------------------------

## Creating numpy array

In [2]:
arr1 = np.array([2,5,6,7,8]) #creating n-d array

In [3]:
arr2 = np.array([[2,5,8,3],[3,5,6,3],[5,6,8,1]]) #2D array

In [4]:
arr3 = np.zeros(5)

In [5]:
arr4 = np.ones(10)

In [32]:
arr5 = np.arange(20) #creating array from 0 to 10

In [7]:
arr6 = np.linspace(11, 51, 5) #creating array with in a range ----> start_element = 11, last_element = 50, no of element = 5

In [8]:
arr7 = np.empty(5) #empty array -----> 6 columns

In [28]:
arr8 = np.identity(11, dtype = np.int16) #identity matrix

----------------------------------------------------------------------------------------------------

## Basic properties of numpy array

In [9]:
arr1

array([2, 5, 6, 7, 8])

In [10]:
print(arr1)
print(type(arr1))

[2 5 6 7 8]
<class 'numpy.ndarray'>


In [11]:
arr1[3] #accessig element

7

In [12]:
arr1.shape #identifiy the shape of array

(5,)

In [13]:
arr1.dtype #data type of the array

dtype('int32')

In [14]:
arr1.size #size of array

5

---------------------------------------------------------------------------------------------------------------------------

In [15]:
arr2

array([[2, 5, 8, 3],
       [3, 5, 6, 3],
       [5, 6, 8, 1]])

In [16]:
print(arr2[1][2])

6


In [37]:
arr2.ravel() #change into 1D array

array([2, 5, 8, 3, 3, 5, 6, 3, 5, 6, 8, 1])

-----------------------------------------------------------------------------------------------------

In [17]:
arr3

array([0., 0., 0., 0., 0.])

---------------------------------------------------------------------------------------------------

In [18]:
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

------------------------------------------------------------

In [33]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr5.reshape(4,5) #reshaping the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

----------------------------

In [20]:
arr6

array([11., 21., 31., 41., 51.])

----------------------------------------------------

In [23]:
arr7

array([2.12199579e-314, 9.33678148e-312, 5.92878775e-321, 6.95293224e-310,
       0.00000000e+000])

----------------------------------

In [29]:
arr8

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int16)

---------------------------------------------------------------------

## Functions & attribute in numpy array

In [39]:
arr = np.array([[4,5,7,2],[5,7,1,3],[6,8,9,0]])

In [41]:
arr

array([[4, 5, 7, 2],
       [5, 7, 1, 3],
       [6, 8, 9, 0]])

In [42]:
arr.sum(axis = 0)

array([15, 20, 17,  5])

In [43]:
arr.sum(axis = 1)

array([18, 16, 23])

In [44]:
arr.T #transpose of matrix

array([[4, 5, 6],
       [5, 7, 8],
       [7, 1, 9],
       [2, 3, 0]])

In [45]:
for item in arr.flat: #Accessing all element
    print(item,end = " ")

4 5 7 2 5 7 1 3 6 8 9 0 

In [47]:
arr.ndim #dimention of array

2

In [48]:
arr.size

12

In [49]:
arr.nbytes #total byte using in array

48

---------------------------------------

In [55]:
one = np.array([4,0,11,4,7,2,0,15])

In [56]:
one.argmax() #index of a maximum element in array

7

In [57]:
one.argmin() #index of a minimum element in array

1

In [58]:
one.argsort() #sorting the array(give us index)

array([1, 6, 5, 0, 3, 4, 2, 7], dtype=int64)

------------------------------------------------------------------------



In [62]:
arr

array([[4, 5, 7, 2],
       [5, 7, 1, 3],
       [6, 8, 9, 0]])

In [59]:
arr.argmax()

10

In [86]:
arr.max()

9

In [61]:
arr.argmin()

11

In [87]:
arr.min()

0

In [63]:
arr.argsort()

array([[3, 0, 1, 2],
       [2, 3, 0, 1],
       [3, 0, 1, 2]], dtype=int64)

In [89]:
arr.sort()
arr

array([[2, 4, 5, 7],
       [1, 3, 5, 7],
       [0, 6, 8, 9]])

In [64]:
arr.argmax(axis = 0)

array([2, 2, 2, 1], dtype=int64)

In [68]:
arr.argmax(axis = 1)

array([2, 1, 2], dtype=int64)

In [65]:
arr.argmin(axis = 0)

array([0, 0, 1, 2], dtype=int64)

In [69]:
arr.argmin(axis = 1)

array([3, 2, 3], dtype=int64)

In [66]:
arr.argsort(axis = 0)

array([[0, 0, 1, 2],
       [1, 1, 0, 0],
       [2, 2, 2, 1]], dtype=int64)

In [67]:
arr.argsort(axis = 1)

array([[3, 0, 1, 2],
       [2, 3, 0, 1],
       [3, 0, 1, 2]], dtype=int64)

---------------------------------------------------------

## Mathematical operation

In [75]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [76]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [78]:
a+b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [80]:
a-b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [81]:
a*b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [82]:
a/b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [83]:
a//b

array([[0, 0, 0],
       [0, 1, 1],
       [2, 4, 9]])

In [85]:
a%b

array([[1, 2, 3],
       [4, 0, 2],
       [1, 0, 0]])

In [90]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [91]:
np.sum(a)

45

In [93]:
a.max()

9

In [94]:
a.min()

1

In [97]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [95]:
np.where(a>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [98]:
np.count_nonzero(a)

9

In [99]:
np.nonzero(a)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

-------------------------------

## Indexing and slicing

In [104]:
data = np.arange(0,20)

In [105]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [110]:
data[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [114]:
data[-5:]

array([15, 16, 17, 18, 19])

In [116]:
print(data[data<5])

[0 1 2 3 4]


----------------

## How to get unique items and counts

In [124]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [125]:
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [126]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [127]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [128]:
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [129]:
np.unique(a_2d, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [130]:
np.unique(a_2d, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

------------------------------------

## How to reverse an array

In [131]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [132]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [133]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [134]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [135]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [136]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])