In [2]:
import numpy as np

------------------------------------------------------------------------------------------------------------------------

## Creating numpy array

In [98]:
arr1 = np.array([2,5,6,7,8,9]) #creating n-d array

In [3]:
arr2 = np.array([[2,5,8,3],[3,5,6,3],[5,6,8,1]]) #2D array

In [3]:
np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]) #3D array`

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [4]:
arr3 = np.zeros(5) #creating array contain only zeros(0)

In [5]:
arr4 = np.ones(10) #creating array contain only one(1)

In [6]:
arr5 = np.arange(20) #creating array from 0 to 10
print(np.arange(10,20)) # creating array from 10 to 20
print(np.arange(10,20,3)) #2 gap between 2 element

[10 11 12 13 14 15 16 17 18 19]
[10 13 16 19]


In [7]:
arr6 = np.linspace(11, 51, 5) #creating array with in a range ----> start_element = 11, last_element = 50, no of element = 5

In [8]:
arr7 = np.empty(5) #empty array with random data -----> 6 columns

In [9]:
arr8 = np.identity(11, dtype = np.int16) #identity matrix

In [152]:
rng = np.random.default_rng()
rng.random((5,5))

array([[0.62448152, 0.39654329, 0.26469518, 0.62000266, 0.0085022 ],
       [0.17687246, 0.12976347, 0.27603898, 0.72485501, 0.01695881],
       [0.01746715, 0.17473997, 0.33135891, 0.56462519, 0.08658989],
       [0.7059114 , 0.18640997, 0.80010021, 0.94517074, 0.04150622],
       [0.73593209, 0.6931233 , 0.21089803, 0.6570498 , 0.36968683]])

----------------------------------------------------------------------------------------------------

## Basic properties of numpy array

In [99]:
arr1

array([2, 5, 6, 7, 8, 9])

In [100]:
print(arr1)
print(type(arr1))

[2 5 6 7 8 9]
<class 'numpy.ndarray'>


In [101]:
arr1[3] #accessig element

7

In [102]:
arr1.shape #identifiy the shape of array

(6,)

In [103]:
arr1.dtype #data type of the array

dtype('int32')

In [104]:
arr1.size #size of array

6

In [105]:
arr1.ndim #return dimention of the array

1

In [106]:
arr1.reshape(3,2)

array([[2, 5],
       [6, 7],
       [8, 9]])

---------------------------------------------------------------------------------------------------------------------------

In [16]:
arr2

array([[2, 5, 8, 3],
       [3, 5, 6, 3],
       [5, 6, 8, 1]])

In [17]:
print(arr2[1][2])

6


In [18]:
arr2.ravel() #change into 1D array

array([2, 5, 8, 3, 3, 5, 6, 3, 5, 6, 8, 1])

-----------------------------------------------------------------------------------------------------

In [19]:
arr3

array([0., 0., 0., 0., 0.])

---------------------------------------------------------------------------------------------------

In [20]:
arr4

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

------------------------------------------------------------

In [21]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [22]:
arr5.reshape(4,5) #reshaping the array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

----------------------------

In [23]:
arr6

array([11., 21., 31., 41., 51.])

----------------------------------------------------

In [24]:
arr7

array([1.43172303e-311, 1.43172657e-311, 1.43172656e-311, 1.43172657e-311,
       0.00000000e+000])

----------------------------------

In [25]:
arr8

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]], dtype=int16)

---------------------------------------------------------------------

## Functions & attribute in numpy array

In [26]:
arr = np.array([[4,5,7,2],[5,7,1,3],[6,8,9,0]])

In [27]:
arr

array([[4, 5, 7, 2],
       [5, 7, 1, 3],
       [6, 8, 9, 0]])

In [28]:
arr.sum(axis = 0)

array([15, 20, 17,  5])

In [29]:
arr.sum(axis = 1)

array([18, 16, 23])

In [30]:
arr.T #transpose of matrix

array([[4, 5, 6],
       [5, 7, 8],
       [7, 1, 9],
       [2, 3, 0]])

In [31]:
for item in arr.flat: #Accessing all element
    print(item,end = " ")

4 5 7 2 5 7 1 3 6 8 9 0 

In [32]:
arr.ndim #dimention of array

2

In [33]:
arr.size

12

In [34]:
arr.nbytes #total byte using in array

48

---------------------------------------

In [35]:
one = np.array([4,0,11,4,7,2,0,15])

In [36]:
one.argmax() #index of a maximum element in array

7

In [37]:
one.argmin() #index of a minimum element in array

1

In [38]:
one.argsort() #sorting the array(give us index)

array([1, 6, 5, 0, 3, 4, 2, 7], dtype=int64)

------------------------------------------------------------------------



In [39]:
arr

array([[4, 5, 7, 2],
       [5, 7, 1, 3],
       [6, 8, 9, 0]])

In [40]:
arr.argmax()

10

In [41]:
arr.max()

9

In [42]:
arr.argmin()

11

In [43]:
arr.min()

0

In [44]:
arr.argsort()

array([[3, 0, 1, 2],
       [2, 3, 0, 1],
       [3, 0, 1, 2]], dtype=int64)

In [45]:
arr.sort()
arr

array([[2, 4, 5, 7],
       [1, 3, 5, 7],
       [0, 6, 8, 9]])

In [46]:
arr.argmax(axis = 0)

array([0, 2, 2, 2], dtype=int64)

In [47]:
arr.argmax(axis = 1)

array([3, 3, 3], dtype=int64)

In [48]:
arr.argmin(axis = 0)

array([2, 1, 0, 0], dtype=int64)

In [49]:
arr.argmin(axis = 1)

array([0, 0, 0], dtype=int64)

In [50]:
arr.argsort(axis = 0)

array([[2, 1, 0, 0],
       [1, 0, 1, 1],
       [0, 2, 2, 2]], dtype=int64)

In [51]:
arr.argsort(axis = 1)

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]], dtype=int64)

---------------------------------------------------------

## Mathematical operation

In [91]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[9,8,7],[6,5,4],[3,2,1]])

In [92]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [94]:
np.concatenate((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [95]:
np.concatenate((a,b), axis = 0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [96]:
np.concatenate((a,b), axis = 1)

array([[1, 2, 3, 9, 8, 7],
       [4, 5, 6, 6, 5, 4],
       [7, 8, 9, 3, 2, 1]])

In [107]:
a+b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [108]:
a-b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [109]:
a*b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

In [110]:
a/b

array([[0.11111111, 0.25      , 0.42857143],
       [0.66666667, 1.        , 1.5       ],
       [2.33333333, 4.        , 9.        ]])

In [111]:
a//b

array([[0, 0, 0],
       [0, 1, 1],
       [2, 4, 9]])

In [112]:
a%b

array([[1, 2, 3],
       [4, 0, 2],
       [1, 0, 0]])

In [113]:
a*2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [114]:
a+3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [115]:
a-4

array([[-3, -2, -1],
       [ 0,  1,  2],
       [ 3,  4,  5]])

In [116]:
a/10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

In [117]:
a//10

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [118]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [133]:
np.sum(a)

45

In [134]:
a.sum() #sum of all array

45

In [135]:
a.sum(axis = 0) 

array([12, 15, 18])

In [136]:
a.sum(axis = 1)

array([ 6, 15, 24])

In [120]:
a.max() #max value from array

9

In [137]:
a.max(axis = 0)

array([7, 8, 9])

In [138]:
a.max(axis = 1)

array([3, 6, 9])

In [121]:
a.min() #min value from array

1

In [139]:
a.min(axis = 0)

array([1, 2, 3])

In [140]:
a.min(axis = 1)

array([1, 4, 7])

In [122]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [123]:
np.where(a>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [124]:
np.count_nonzero(a)

9

In [68]:
np.nonzero(a)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

-------------------------------

## Indexing and slicing

In [69]:
data = np.arange(0,20)

In [70]:
data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [71]:
data[5:11]

array([ 5,  6,  7,  8,  9, 10])

In [72]:
data[-5:]

array([15, 16, 17, 18, 19])

In [73]:
print(data[data<5])

[0 1 2 3 4]


In [126]:
data = data.reshape(4,5)

In [127]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [132]:
np.hsplit(data,(5,2))

[array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]),
 array([], shape=(4, 0), dtype=int32),
 array([[ 2,  3,  4],
        [ 7,  8,  9],
        [12, 13, 14],
        [17, 18, 19]])]

----------------

## How to get unique items and counts

In [74]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [75]:
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [76]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [77]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])

In [78]:
np.unique(a_2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [79]:
np.unique(a_2d, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [80]:
np.unique(a_2d, axis=1)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

------------------------------------

## How to reverse an array

In [81]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [82]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

In [83]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [84]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [85]:
np.flip(arr_2d, axis=1)

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [86]:
np.flip(arr_2d, axis=0)

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

---------------------------------

## save and load the array

In [153]:
data = np.arange(0,50).reshape(10,5)

In [157]:
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [158]:
np.savetxt('new_file.csv',data)

In [159]:
np.loadtxt('new_file.csv')

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.],
       [25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34.],
       [35., 36., 37., 38., 39.],
       [40., 41., 42., 43., 44.],
       [45., 46., 47., 48., 49.]])